server:
  port: 8080

spring:
  application:
    name: reptiles-server

#  redis:
#    host: 172.16.1.24
#    port: 6379

  datasource:
    url: jdbc:mysql://172.16.1.2:3306/public?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
